sudo: required
language: node_js
node_js:
  - "6.9"
  - "7"

  addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_script:
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - 'node_modules/protractor/bin/webdriver-manager update &'
  - sleep 10
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - sleep 5
  - echo 'db.addUser("admin", "admin");' | mongo test-storage

install:
  - yarn
services:
  - mongodb
