sudo: required
dist: trusty
group: edge
language: node_js
node_js:
  - "8"

services:
  - mongodb

before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - 'node_modules/protractor/bin/webdriver-manager update &'
  - sleep 10
  - 'node_modules/protractor/bin/webdriver-manager start 2>&1 &'
  - sleep 5

before_script:
  - sleep 5
  - mongo test-storage install/db-init.js

script:
  # Output useful info for debugging.
  - node --version && npm --version && ng --version
  # linting
  - npm run lint
  # Run tests
  - npm test

install:
  - npm install

