# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

build: off

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

services:
  - mongodb

before_test:
  - sleep 10
  - C:\mongodb\bin\mongo test-storage install/db-init.js

test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # linting
  - npm run lint
  # Run tests
  # npm test


