environment:
  matrix:
    - nodejs_version: "4.0"
    - nodejs_version: "4.4"
    - nodejs_version: "5.11"
    - nodejs_version: "6.0"
    - nodejs_version: "6.1"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
services:
  - mongodb
build: off
test_script:
  - node --version
  - npm --version
  - npm test

