# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Test against this version of Node.js
environment:
  matrix:
    - nodejs_version: "6.9"
    - nodejs_version: "7"

build: off

# Fix line endings on Windows
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

services:
  - mongodb

test_script:
  # Output useful info for debugging.
  - node --version && npm --version && yarn --version
  # Run tests
  - npm run testserver

cache:
  - node_modules
  - "%LOCALAPPDATA%/Yarn"

